apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kube-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: shapes.com
    http:
      paths:
      - path: /kubes/(.*)
        backend:
          serviceName: kube-demo-service
          servicePort: 8000

      - path: /cirkles/(.*)
        backend:
          serviceName: cirkle-demo-service
          servicePort: 8000
