apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-demo
    template:
      metadata:
        labels:
          app: kube-demo
      spec:
        containers:
          - name: kube-demo
            image: tmdeal/kube-demo
            ports:
              - containerPort: 8000
