apiVersion: batch/v1
kind: Job
metadata:
  name: cirkle-demo-migrations
spec:
  template:
    spec:
      containers:
        - name: cirkle-demo-migrations
          image: tmdeal/cirkle-demo:latest
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

            - name: POSTGRES_DB
              value: cirkle
      restartPolicy: Never
  backoffLimit: 5
