apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  initdb.sql: |
    SELECT 'CREATE DATABASE kube' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'kube')\gexec
    SELECT 'CREATE DATABASE cirkle' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'cirkle')\gexec
