# Generated by Django 3.0.2 on 2020-01-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('color', models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default='black', max_length=255)),
            ],
        ),
    ]
